[versions]
agp = "8.9.2"
kotlin = "2.1.0"
ksp = "2.1.0-1.0.29"
kotlinCompose = "2.1.0"
navigation = "2.9.0"

hilt = "2.57.2"
room = "2.8.4"
compose = "1.10.0"
compose-bom = "2024.05.00"
activity-compose = "1.12.0-alpha01"
lifecycle = "2.9.1"
core-ktx = "1.16.0"
lifecycleViewmodel = "1.0.0-alpha04"
accompanist = "0.36.0"
material3 = "1.4.0-rc01"
material-icons = "1.7.8"
serialization = "1.9.0"
retrofit = "3.0.0"
okhttp = "4.12.0"
okhttp-logging = "4.12.0"

# test:
mockito-core = "5.18.0"
mockito-kotlin = "5.4.0"
coroutines-test = "1.10.2"
junit = "4.13.2"
androidx-junit = "1.2.1"
espresso = "3.6.1"
navigation-testing = "2.9.0"
test-core = "1.6.1"
appcompat = "1.7.1"
coil-version = "2.4.0"

[libraries]
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil-version" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }

lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }


# navigation
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodel" }
navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigation-testing" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.3.0" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }


accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }


room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-logging" }

serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
test-core = { module = "androidx.test:core", version.ref = "test-core" }

coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-test" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockito-core" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }


[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinCompose" }